spring:
  application:
    name: final-project
  datasource:
    url: jdbc:postgresql://localhost:5432/final-project
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 5000
  servlet:
    context-path: /api/v1
