version: '3.8'

services:
  postgres:
    image: postgres
    container_name: final-project
    environment:
      POSTGRES_DB: final-project
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: